### ISSUE TITLE
docker-ce package pin

### ISSUE THREAD

**Issue by dragonsmith** [evilmartians/chef-kubernetes#14]
`docker-ce` package version pin is broken on Ubuntu 16:

```shell
# apt-cache policy docker-ce | grep '\*\*\*'
 *** 17.03.2~ce-0~ubuntu-xenial 500
# cat /etc/apt/preferences.d/docker-ce.pref
Package: docker-ce
Pin: version 17.03.2~ubuntu-xenial
Pin-Priority: 700```

**Comment by Bregor** [comment]
# apt-cache madison docker-ce|grep -E '17.[0-9\.]+~ce-0~ubuntu '
    docker-ce | 17.12.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
    docker-ce | 17.12.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
    docker-ce | 17.09.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
    docker-ce | 17.09.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
    docker-ce | 17.06.2~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
    docker-ce | 17.06.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
    docker-ce | 17.06.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages

There is no more `17.03~ce-0~ubuntu` in main repo.

**Comment by Bregor** [comment]
Fixed in https://github.com/evilmartians/chef-kubernetes/commit/d75d5e5190710b5afa47d11bfd1efde046ab6bb7
